name: 'dwh_kimball'
version: '1.0.0'

profile: 'dwh_kimball'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwh_kimball:
    staging:
      +schema: staging

